## SPRING SETTINGS
spring:
    main:
        allow-bean-definition-overriding: true
    thymeleaf:
        mode: HTML5
        encoding: UTF-8

    data.jpa.repositories.enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/memberregistration
        username: memberregistration
        password: memberregistration
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate.ddl-auto: create
        properties.hibernate.default_schema: PUBLIC
        show-sql: false
    security:
        oauth2:
            client:
                provider:
                    wisvchconnect:
                        issuer-uri: https://connect.ch.tudelft.nl
                registration:
                    wisvchconnect:
                        client-id: localhost-spring-dev
                        client-secret: Hvw51WUpYdSRhJ6hrxNSNQyXK0jv3M6-dRxVhfUhEuVz9PvH8hVMz51SeGajsIVT_C5l0KyzjrnfvNyGzbiW3A
                        scope:
                            - openid
                            - profile
                            - email
                            - ldap

server:
    port: 9000
    servlet:
        context-path: /api


# Spring Boot Actuator endpoint settings
management:
    endpoints:
        web:
            base-path: /management
    endpoint:
        logfile:
            enabled: true

wisvch.connect:
    # Change <MyLDAPgroup> to a LDAP group you're in (e.g. hoothub, dienst2, etc.)
    admin-groups: hoothub

# CH Payments Configuration
wisvch.payments:
    issuerUri: http://localhost:8080/payments
    clientUri: http://localhost:9000/member
